apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-pv
  namespace: k8s-api-go
  labels:
    app: postgres
spec:
  storageClassName: microk8s-hostpath
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/var/data"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pv-claim
  namespace: k8s-api-go
  labels:
    app: postgres
spec:
  storageClassName: microk8s-hostpath
  capacity:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-configuration
  namespace: k8s-api-go
  labels:
    app: postgres
data:
  POSTGRES_DB: jrmanes
  POSTGRES_USER: jrmanes
  POSTGRES_PASSWORD: jrmanes
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres
  namespace: k8s-api-go
spec:
  serviceName: "postgres"
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:latest
          envFrom:
            - configMapRef:
                name: postgres-configuration
          resources:
            limits:
              cpu: 750m
              memory: 700Mi
            requests:
              cpu: 450m
              memory: 450Mi
          ports:
            - containerPort: 5432
              name: postgresdb
          volumeMounts:
            - name: pv-data
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: pv-data
          persistentVolumeClaim:
            claimName: postgres-pv-claim
---
apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: k8s-api-go
  labels:
    app: postgres
spec:
  ports:
    - port: 5432
      name: postgres
  clusterIP: None
  selector:
    app: postgres
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-svc
  namespace: k8s-api-go
  labels:
    app: postgres
spec:
  ports:
    - port: 5432
      name: postgres
  type: NodePort
  selector:
    app: postgres