apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-api-go
  namespace: k8s-api-go
spec:
  selector:
    matchLabels:
      app: k8s-api-go
  replicas: 1
  template:
    metadata:
      labels:
        app: k8s-api-go
    spec:
      containers:
        - name: k8s-api-go
          image: jrmanes/k8s-api-go:latest
          env:
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: k8s-api-go-secret
                  key: DB_USER
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: k8s-api-go-secret
                  key: DB_PASSWORD
            - name: DB_DRIVER
              value: "postgres"
            - name: DB_HOST
              value: "postgres-svc"
            - name: DB_NAME
              value: "jrmanes"
            - name: DB_PORT
              value: "5432"
            - name: DATABASE_MIGRATIONS
              value: "true"
            - name: ENV
              value: "dev"
            - name: SERVER_PORT
              value: "8080"
            - name: DATABASE_URI
              value: "$DB_DRIVER://$DB_USER:$DB_PASSWORD@$DB_HOST:$DB_PORT/$DB_NAME?&sslmode=disable"
          resources:
            limits:
              cpu: 450m
              memory: 512Mi
            requests:
              cpu: 250m
              memory: 252Mi
          ports:
            - containerPort: 8080
          imagePullPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: k8s-api-go-svc
  namespace: k8s-api-go
  labels:
    app: k8s-api-go
spec:
  ports:
    - port: 8080
      name: k8s-api-go
  type: NodePort
  selector:
    app: k8s-api-go
---
apiVersion: v1
kind: Secret
metadata:
  name: k8s-api-go-secret
  namespace: k8s-api-go
type: Opaque
data:
  DB_PASSWORD: anJtYW5lcw==
  DB_USER: anJtYW5lcw==